name: Production Deployment Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-deployment-checks:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔨 Build project
        run: npm run build

      - name: 🧪 Run tests
        run: npm test
        env:
          NODE_ENV: test
          MONGODB_URI: mongodb://localhost:27017/neurlyn-test

      - name: 🔒 Security audit
        run: npm audit --audit-level=moderate

      - name: 📊 Check bundle size
        run: |
          echo "Checking bundle sizes..."
          du -sh dist/* | head -20

      - name: ✅ Deployment ready
        run: |
          echo "✅ All checks passed!"
          echo "Vercel will automatically deploy from GitHub integration"
          echo "Domain: neurlyn.com"
