name: Production Deployment Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-deployment-checks:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔨 Build project
        run: npm run build

      - name: 🧪 Run tests
        run: npm test

      - name: 🔒 Security audit
        run: npm audit --audit-level=moderate

      - name: 📊 Check bundle size
        run: |
          echo "Checking bundle sizes..."
          du -sh dist/* | head -20

      - name: ✅ Deployment ready
        run: |
          echo "✅ All checks passed!"
          echo "Vercel will automatically deploy from GitHub integration"
          echo "Domain: neurlyn.com"
